- authomatic/providers/__init__.py
Fix `AttributeError: type object 'GitHub' has no attribute '_logger'` reusing the GitHub provider with deserialized credentials.
Sounds the same as: https://github.com/peterhudec/authomatic/issues/1#issuecomment-60454907
> Fix attribute error falling back to core logger

- authomatic/providers/openid.py
I was getting an error
import() argument 1 must be string without null bytes, not str
when using Yahoo OpenID. Something in pickle wasn't happy it seemed, but this appears to resolve it
> Yahoo OpenID error

- authomatic/__init__.py
Using absolute import (`import six`) doesn't seems to work with python3 if six is not installed, relative import fix the issue.
I think you should release a new version on pypi with this fix (or add six as an explicit dependency) given the python3 version is broken without it, see the output of my `pip install -r requirement.txt`:
```
Downloading/unpacking authomatic (from -r requirements.txt (line 6))
Downloading Authomatic-0.0.11.tar.gz (814kB): 814kB downloaded
Running setup.py (path:/home/rof/src/github.com/Scille/vigiechiro-api/venv/build/authomatic/setup.py) egg_info for package authomatic
Traceback (most recent call last):
File "<string>", line 17, in <module>
File "/home/rof/src/github.com/Scille/vigiechiro-api/venv/build/authomatic/setup.py", line 3, in <module>
from authomatic …
```
> Correct six local import for python3 compatibility

- authomatic/core.py
- authomatic/providers/__init__.py
This patch checks to see if content returned from http request is binary and skips decoding step if it is. this prevents decoding binary data as utf-8 from raising an exception
> test for binary response content, skip decoding if it is. closes #87

- authomatic/providers/__init__.py
Since d87b076 (after 0.0.10 and before 0.0.11) Authomatic can't handle responses with non-ascii chars quite well and fails with:
```
Traceback (most recent call last):
[snippet]
File "/Wrokspace/authomatic/authomatic/core.py", line 554, in update
return self.provider.update_user()
File "/Wrokspace/authomatic/authomatic/providers/__init__.py", line 784, in update_user
return self._access_user_info()
File "/Wrokspace/authomatic/authomatic/providers/__init__.py", line 887, in _access_user_info
response = self.access(url)
File "/Wrokspace/authomatic/authomatic/providers/__init__.py", line 752, in access
self._log(logging.INFO, 'Got response. HTTP status = {0}. {1}'.format(response.status, response.content))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 11: …
```
> provider: do not log content, it may contain non-ascii chars

- authomatic/providers/oauth2.py
Hello. 
Facebook may redirect with error, which cause exception
TypeError("argument of type 'NoneType' is not iterable",)
because error_reason is still None. This patch fixes this exception.
You may reproduce the error if Facebook answers the following:
"Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains."
> Facebook: do not except if error_reason and error are None

- authomatic/adapters.py
HttpRequest.REQUEST is deprecated on django >= 1.7
> It adds support for django >= 1.7

- authomatic/providers/oauth1.py
If the user who was trying to authenticate/login hasn't activated the Yahoo Profile (i.e., has an old/unused Yahoo account), the Authomatic.user.update() method was returning an error (probably because old profiles don't have location data):
```
File "../lib/python2.7/site-packages/authomatic/providers/oauth1.py", line 785, in _x_user_parser
user.city, user.country = _user.get('location', ',').split(',')
ValueError: need more than 1 value to unpack
```
I fix the bug with a try/exception clause to avoid impeding the authentication due to the lack of a comma in the location info Yahoo was sending.
> Fix bug for old Yahoo! profiles

- CHANGES.rst
- authomatic/providers/oauth1.py
Adds support for BitBucket email property by fetching available emails and selecting one marked as primary.
> Add support for user email in Bitbucket provider

- authomatic/providers/oauth2.py
A simple update to explicitly request fields from facebook. (Fixes #130)
This PR only requests fields that were previously provided implicitly. Requesting 'new' fields should be a separate feature PR.
> Explicitly request FB fields.

- authomatic/providers/oauth2.py
Augments state variable in oauth2 to support a user_state component in addition to existing csrf cookie.  Invoke login with query parameter user_state, which will be incorporated into state variable and passed through by provider.  Returned state variable can be decoded to retrieve supplied user_state using OAuth2.decode_state.
Can be used to address issues #63, #70 and #108.
> Support passing of user state in oauth2 to support variable redirect urls

- authomatic/providers/oauth1.py
profile_image_url is missing from the response unless we provide parameter include_entities=true
> Fix Twitter user info endpoint

- CHANGES.rst
- authomatic/providers/oauth1.py
Add `include_email=True` url param to request emails form twitter as requested in #140. Twitter reference: https://dev.twitter.com/rest/reference/get/account/verify_credentials
> Request email from Twitter. Fixes #140.

- doc/source/examples/index.rst
- doc/source/examples/providers.rst
- tests/functional_tests/expected_values/new_provider.py.template
- tests/functional_tests/fixtures/__init__.py
It looks like this branch has never been merged into master, though its content is found in the generated docs at gh-pages and on the live docs: https://authomatic.github.io/authomatic/examples/providers.html
> Create tutorial for providers

- doc/source/conf.py
Fix the incorrect absolute path `/reference/providers` and use the correct relative path `providers` in ReST replace 'alias' `provider_class`
Replaces #98 (which was an equivalent edit to the generated html output).
> Fix ReST replace relative path.

- .travis.yml
- tests/functional_tests/config_public.py
- tests/functional_tests/expected_values/twitter.py
- tests/functional_tests/test_providers.py
- tox.ini
This PR re-enables the `pyramid` framework in testing, using the new release of `liveandletdie` which provides SSL support.
It also instructs `selenium`/`chrome` to ignore certificate errors, logs out of travis between frameworks, and tidies up some of the `travis`/`tox` config.
> Enable Pyramid framework with SSL.

- examples/gae/showcase/static/js/foundation/foundation.forms.js
There is a small typo in examples/gae/showcase/static/js/foundation/foundation.forms.js.
Should read `visible` rather than `visibile`.
> docs: Fix simple typo, visibile -> visible

- README.rst
- doc/source/development.rst
- examples/flask/functional_test/main.py
- examples/gae/showcase/static/js/foundation/foundation.forms.js
- examples/gae/showcase/static/js/foundation/foundation.joyride.js
- tests/functional_tests/expected_values/windowslive.py
There are small typos in:
- README.rst
- doc/source/development.rst
- examples/flask/functional_test/main.py
- examples/gae/showcase/static/js/foundation/foundation.forms.js
- examples/gae/showcase/static/js/foundation/foundation.joyride.js
- tests/functional_tests/expected_values/windowslive.py
Fixes:
- Should read `unless` rather than `unles`.
- Should read `deployment` rather than `deploiment`.
- Should read `configurable` rather than `configureable`.
- Should read `calls` rather than `callls`.
- Should read `calculate` rather than `calcualate`.
- Should read `always` rather than `alwas`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- authomatic/providers/oauth2.py
I've tested this with pas.plugins.authomatic for logging into a Plone site. By default it assumes a multi-tenant app (anyone with an MS account). For single-tenant app, the domain of the tenant should be passed as a configuration parameter (¨domain¨).
> Add adapter for Microsoft Online (Azure AD)

- authomatic/providers/__init__.py
PR to implement fix of `ssl` deprecating/removing `cert_file` in py3.11+ in favour of `context` (introduced in py3.4)
> ssl cert_file has been replaced with contexts. Fixes #235.
